'''
ProjectEuler Problem 29

Mikael Fors 2014

"How many distinct terms are in the sequence generated by a**b for 2 <= a <= 100
 and 2 <= b <= 100?"
'''

print len({a ** b for a in xrange(2, 101) for b in xrange(2, 101)})
